import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Main documentation sidebar
  tutorialSidebar: [
    {
      type: 'category',
      label: '📖 Getting Started',
      items: [
        {
          type: 'autogenerated',
          dirName: '01-getting-started',
        },
      ],
    },
    {
      type: 'category',
      label: '📚 Guides',
      items: [
        {
          type: 'autogenerated',
          dirName: '02-guides',
        },
      ],
    },
    {
      type: 'category',
      label: '🔌 API Reference',
      items: [
        'api/intro',
        {
          type: 'category',
          label: 'REST & WebSocket APIs',
          items: [
            {
              type: 'autogenerated',
              dirName: '03-api-reference',
            },
          ],
        },
        {
          type: 'category',
          label: 'Backend API (Python)',
          items: [
            {
              type: 'autogenerated',
              dirName: 'api/backend',
            },
          ],
        },
        {
          type: 'category',
          label: 'Frontend API (TypeScript)',
          link: {
            type: 'doc',
            id: 'api/frontend/README',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'api/frontend',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: '🏗️ Architecture',
      items: [
        {
          type: 'autogenerated',
          dirName: '04-architecture',
        },
      ],
    },
    {
      type: 'category',
      label: '📋 Specifications',
      items: [
        {
          type: 'autogenerated',
          dirName: '05-specifications',
        },
      ],
    },
    {
      type: 'category',
      label: '⚙️ Operations',
      items: [
        {
          type: 'autogenerated',
          dirName: '06-operations',
        },
      ],
    },
    {
      type: 'category',
      label: '🗂️ Project',
      items: [
        {
          type: 'autogenerated',
          dirName: '07-project',
        },
      ],
    },
    {
      type: 'category',
      label: '🤝 Contributing',
      items: [
        {
          type: 'autogenerated',
          dirName: '08-contributing',
        },
      ],
    },
  ],
};

export default sidebars;
