#!/usr/bin/env bash
# ============================================================================
# Blue-Green Deployment Script for Stock Screening Platform
# ============================================================================
# Achieves zero-downtime deployment by running two backend slots (blue/green)
# and switching Nginx upstream between them.
#
# Flow:
#   1. Determine current active slot (blue or green)
#   2. Pull new images
#   3. Start new slot alongside active slot on alternate port
#   4. Health-check new slot
#   5. Swap Nginx upstream to new slot, reload Nginx (graceful)
#   6. Stop old slot
#
# Usage:
#   ./scripts/deploy-bluegreen.sh \
#     --environment staging \
#     --image-tag <sha> \
#     --registry ghcr.io \
#     --backend-image ghcr.io/org/repo/backend \
#     --frontend-image ghcr.io/org/repo/frontend \
#     --github-token <token> \
#     --github-actor <actor>
#
#   ./scripts/deploy-bluegreen.sh --environment staging --rollback
# ============================================================================

set -euo pipefail

# ============================================================================
# Configuration
# ============================================================================

DEPLOY_DIR="$HOME/screener"
STATE_FILE="$DEPLOY_DIR/.bluegreen-state"
LOG_FILE="$DEPLOY_DIR/.deploy.log"
NGINX_UPSTREAM_DIR="$DEPLOY_DIR/infrastructure/nginx/conf.d"
NGINX_UPSTREAM_FILE="$NGINX_UPSTREAM_DIR/upstream-backend.conf"
NGINX_CONTAINER="screener_nginx"

BLUE_PORT=8000
GREEN_PORT=8001

RED='\033[0;31m'
GREEN_C='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# ============================================================================
# Argument Parsing
# ============================================================================

ENVIRONMENT=""
IMAGE_TAG=""
REGISTRY=""
BACKEND_IMAGE=""
FRONTEND_IMAGE=""
GITHUB_TOKEN=""
GITHUB_ACTOR=""
ROLLBACK=false

while [[ $# -gt 0 ]]; do
    case $1 in
        --environment)    ENVIRONMENT="$2"; shift 2 ;;
        --image-tag)      IMAGE_TAG="$2"; shift 2 ;;
        --registry)       REGISTRY="$2"; shift 2 ;;
        --backend-image)  BACKEND_IMAGE="$2"; shift 2 ;;
        --frontend-image) FRONTEND_IMAGE="$2"; shift 2 ;;
        --github-token)   GITHUB_TOKEN="$2"; shift 2 ;;
        --github-actor)   GITHUB_ACTOR="$2"; shift 2 ;;
        --rollback)       ROLLBACK=true; shift ;;
        *) echo "Unknown option: $1"; exit 1 ;;
    esac
done

# ============================================================================
# Helpers
# ============================================================================

log() {
    local timestamp
    timestamp=$(date '+%Y-%m-%d %H:%M:%S')
    echo -e "[$timestamp] $1" | tee -a "$LOG_FILE"
}

die() {
    log "${RED}ERROR: $1${NC}"
    exit 1
}

get_compose_file() {
    case "$ENVIRONMENT" in
        staging)    echo "$DEPLOY_DIR/docker-compose.staging.yml" ;;
        production) echo "$DEPLOY_DIR/docker-compose.prod.yml" ;;
        *) die "Unknown environment: $ENVIRONMENT" ;;
    esac
}

get_active_slot() {
    if [ -f "$STATE_FILE" ]; then
        cat "$STATE_FILE"
    else
        echo "none"
    fi
}

get_next_slot() {
    local active
    active=$(get_active_slot)
    case "$active" in
        blue)  echo "green" ;;
        green) echo "blue" ;;
        *)     echo "blue" ;;
    esac
}

get_slot_port() {
    case "$1" in
        blue)  echo "$BLUE_PORT" ;;
        green) echo "$GREEN_PORT" ;;
        *) die "Invalid slot: $1" ;;
    esac
}

# ============================================================================
# Nginx Upstream Management
# ============================================================================

write_upstream() {
    local port="$1"
    mkdir -p "$NGINX_UPSTREAM_DIR"

    cat > "$NGINX_UPSTREAM_FILE" <<EOF
# Auto-generated by deploy-bluegreen.sh — do not edit manually
upstream backend_api {
    least_conn;
    server backend:${port} max_fails=3 fail_timeout=30s;
    keepalive 32;
}
EOF
    log "Nginx upstream updated to port ${port}"
}

reload_nginx() {
    if docker ps --format '{{.Names}}' | grep -q "$NGINX_CONTAINER"; then
        docker exec "$NGINX_CONTAINER" nginx -s reload 2>&1 | tee -a "$LOG_FILE"
        log "${GREEN_C}Nginx reloaded gracefully${NC}"
    else
        log "${YELLOW}Nginx container not found, skipping reload${NC}"
    fi
}

# ============================================================================
# Health Check
# ============================================================================

health_check() {
    local port="$1"
    local max_retries="${2:-15}"
    local interval="${3:-4}"

    log "Running health checks on port ${port}..."

    for i in $(seq 1 "$max_retries"); do
        local http_status
        http_status=$(curl -s -o /dev/null -w "%{http_code}" "http://localhost:${port}/v1/health" 2>/dev/null || echo "000")
        if [ "$http_status" = "200" ]; then
            log "${GREEN_C}Health check passed (attempt $i/$max_retries)${NC}"
            return 0
        fi
        log "Health check attempt $i/$max_retries: HTTP $http_status (waiting ${interval}s...)"
        sleep "$interval"
    done

    log "${RED}Health check failed after $max_retries attempts${NC}"
    return 1
}

# ============================================================================
# Rollback
# ============================================================================

do_rollback() {
    local active
    active=$(get_active_slot)

    if [ "$active" = "none" ]; then
        die "No active slot found. Cannot rollback."
    fi

    # The "rollback" is simply switching back — the previous slot should
    # still be running if a failed deploy didn't clean it up.
    local previous
    previous=$(get_next_slot)  # opposite of active
    local prev_port
    prev_port=$(get_slot_port "$previous")

    log "${YELLOW}Rolling back: switching from $active to $previous (port $prev_port)${NC}"

    # Check if previous slot is still running
    if health_check "$prev_port" 3 2; then
        write_upstream "$prev_port"
        reload_nginx
        echo "$previous" > "$STATE_FILE"
        log "${GREEN_C}Rollback complete — active slot: $previous${NC}"
    else
        die "Previous slot ($previous) is not healthy. Manual intervention required."
    fi
}

# ============================================================================
# Deploy
# ============================================================================

do_deploy() {
    local compose_file
    compose_file=$(get_compose_file)

    local active_slot next_slot next_port
    active_slot=$(get_active_slot)
    next_slot=$(get_next_slot)
    next_port=$(get_slot_port "$next_slot")

    log "============================================"
    log "Blue-Green Deployment to $ENVIRONMENT"
    log "  Active slot:  $active_slot"
    log "  Next slot:    $next_slot (port $next_port)"
    log "  Image tag:    $IMAGE_TAG"
    log "============================================"

    # Step 1: Authenticate with GHCR
    log "Authenticating with container registry..."
    echo "$GITHUB_TOKEN" | docker login "$REGISTRY" -u "$GITHUB_ACTOR" --password-stdin 2>&1 | tee -a "$LOG_FILE"

    # Step 2: Pull new images
    log "Pulling images with tag: $IMAGE_TAG..."
    docker pull "${BACKEND_IMAGE}:${IMAGE_TAG}" 2>&1 | tee -a "$LOG_FILE"
    docker pull "${FRONTEND_IMAGE}:${IMAGE_TAG}" 2>&1 | tee -a "$LOG_FILE"
    log "${GREEN_C}Images pulled successfully${NC}"

    # Step 3: Start new slot
    log "Starting new backend on port ${next_port}..."
    local new_container="screener_backend_${next_slot}"

    # Stop old container for this slot if it exists
    docker rm -f "$new_container" 2>/dev/null || true

    # Run new backend container on the next slot's port
    docker run -d \
        --name "$new_container" \
        --network screener_screener_network \
        -p "127.0.0.1:${next_port}:8000" \
        --env-file "$DEPLOY_DIR/.env" \
        --restart unless-stopped \
        --health-cmd "curl -f http://localhost:8000/health || exit 1" \
        --health-interval 10s \
        --health-timeout 5s \
        --health-retries 3 \
        "${BACKEND_IMAGE}:${IMAGE_TAG}" \
        2>&1 | tee -a "$LOG_FILE"

    # Step 4: Health check new slot
    if ! health_check "$next_port" 15 4; then
        log "${RED}New slot failed health checks. Cleaning up...${NC}"
        docker rm -f "$new_container" 2>/dev/null || true
        die "Deployment aborted — new version is unhealthy"
    fi

    # Step 5: Switch traffic
    log "Switching traffic to $next_slot (port $next_port)..."
    write_upstream "$next_port"
    reload_nginx

    # Step 6: Update state
    echo "$next_slot" > "$STATE_FILE"

    # Step 7: Stop old slot (after brief overlap for in-flight requests)
    if [ "$active_slot" != "none" ]; then
        local old_container="screener_backend_${active_slot}"
        log "Draining old slot ($active_slot) for 5s..."
        sleep 5
        docker rm -f "$old_container" 2>/dev/null || true
        log "Old slot ($active_slot) stopped"
    fi

    # Step 8: Update frontend (can be done normally — static files, no state)
    docker tag "${FRONTEND_IMAGE}:${IMAGE_TAG}" "${FRONTEND_IMAGE}:${ENVIRONMENT}" 2>/dev/null || true
    export FRONTEND_IMAGE="${FRONTEND_IMAGE}:${IMAGE_TAG}"
    export BACKEND_IMAGE="${BACKEND_IMAGE}:${IMAGE_TAG}"
    docker compose -f "$compose_file" up -d --no-deps frontend 2>&1 | tee -a "$LOG_FILE" || true

    log "${GREEN_C}============================================${NC}"
    log "${GREEN_C}Blue-green deployment complete${NC}"
    log "${GREEN_C}  Active slot: $next_slot (port $next_port)${NC}"
    log "${GREEN_C}============================================${NC}"
}

# ============================================================================
# Main
# ============================================================================

mkdir -p "$DEPLOY_DIR"
touch "$LOG_FILE"

[ -z "$ENVIRONMENT" ] && die "--environment is required"

if [ "$ROLLBACK" = true ]; then
    do_rollback
else
    [ -z "$IMAGE_TAG" ] && die "--image-tag is required"
    [ -z "$REGISTRY" ] && die "--registry is required"
    [ -z "$BACKEND_IMAGE" ] && die "--backend-image is required"
    [ -z "$FRONTEND_IMAGE" ] && die "--frontend-image is required"
    [ -z "$GITHUB_TOKEN" ] && die "--github-token is required"
    [ -z "$GITHUB_ACTOR" ] && die "--github-actor is required"
    do_deploy
fi
