#!/usr/bin/env bash
# Initialize Let's Encrypt certificates using certbot
#
# Prerequisites:
#   - Domain DNS must point to this server
#   - Ports 80 and 443 must be accessible from the internet
#   - docker compose must be available
#
# Usage: ./init-letsencrypt.sh <domain> <email>
# Example: ./init-letsencrypt.sh screener.example.com admin@example.com

set -euo pipefail

if [ $# -lt 2 ]; then
    echo "Usage: $0 <domain> <email>"
    echo "Example: $0 screener.example.com admin@example.com"
    exit 1
fi

DOMAIN="$1"
EMAIL="$2"
COMPOSE_FILE="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)/docker-compose.yml"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "=== Let's Encrypt Certificate Setup ==="
echo "Domain: ${DOMAIN}"
echo "Email:  ${EMAIL}"
echo ""

# Step 1: Generate temporary self-signed certificate so Nginx can start
echo "[1/4] Generating temporary self-signed certificate..."
openssl req -x509 -nodes -newkey rsa:2048 \
    -days 1 \
    -keyout "${SCRIPT_DIR}/key.pem" \
    -out "${SCRIPT_DIR}/cert.pem" \
    -subj "/CN=${DOMAIN}" \
    2>/dev/null

# Step 2: Start Nginx (needs a valid cert to start)
echo "[2/4] Starting Nginx..."
docker compose -f "$COMPOSE_FILE" --profile frontend up -d nginx

# Step 3: Request real certificate from Let's Encrypt
echo "[3/4] Requesting certificate from Let's Encrypt..."
docker compose -f "$COMPOSE_FILE" --profile production run --rm certbot \
    certonly --webroot \
    --webroot-path=/var/www/certbot \
    --email "$EMAIL" \
    --agree-tos \
    --no-eff-email \
    -d "$DOMAIN"

# Step 4: Copy Let's Encrypt certs to Nginx SSL directory
echo "[4/4] Linking certificates..."
CERT_SRC="/etc/letsencrypt/live/${DOMAIN}"

# Update Nginx config to use Let's Encrypt certs
cat > "${SCRIPT_DIR}/cert-paths.conf" << EOF
# Auto-generated by init-letsencrypt.sh
# Let's Encrypt certificate paths for ${DOMAIN}
# To use these, update default.conf ssl_certificate directives to:
#   ssl_certificate /etc/nginx/ssl/letsencrypt/live/${DOMAIN}/fullchain.pem;
#   ssl_certificate_key /etc/nginx/ssl/letsencrypt/live/${DOMAIN}/privkey.pem;
EOF

echo ""
echo "=== Setup Complete ==="
echo ""
echo "Certificate obtained for: ${DOMAIN}"
echo ""
echo "Next steps:"
echo "  1. Update infrastructure/nginx/conf.d/default.conf:"
echo "     ssl_certificate /etc/nginx/ssl/letsencrypt/live/${DOMAIN}/fullchain.pem;"
echo "     ssl_certificate_key /etc/nginx/ssl/letsencrypt/live/${DOMAIN}/privkey.pem;"
echo "  2. Restart Nginx: docker compose --profile frontend restart nginx"
echo "  3. Start certbot for auto-renewal: docker compose --profile production up -d certbot"
